### ISSUE TITLE
Can't uninstall!

### ISSUE THREAD

**Issue by RonnyAL** [FireCubeStudios/Rebound#94]
After trying out version 0.0.3 for a while, I've decided that it's not something I want to use for now. However, I can't figure out how to uninstall. It's not showing up under programs and features, "Rebound Hub" returns no results in the start menu (I might have been able to uninstall just that part earlier). Win+R still launches the modified version.

I even searched the registry in the hopes of finding any hints, to no avail. I also redownloaded the installer to see if it'd detect Rebound 11 and offer removal. It doesn't, it just asks if I want to install again.

**Comment by RonnyAL** [comment]
Okay - I reinstalled Rebound Hub and was able to uninstall from there. I chose not to restart. As the (un)installer said that explorer would be restarted, the computer got locked (not logged out, just disconnected). When I logged back in, explorer was gone but never restarted by itself. Had to manually launch it.

Closing the issue anyway since I found a solution.

**Comment by Lamparter** [comment]
Hi @RonnyAL, I'm really sorry you had to experience this!
We're already working on a new build system in #65, feel free to subscribe to its notifications in the sidebar to get updates in your inbox. This build system would allow the app to uninstall itself like a normal app by finding it in the start menu and pressing uninstall.
